extern crate alloc;

use alloc::{boxed::Box, string::String, vec::Vec};

use error::StarkError;
use serde::{Deserialize, Serialize};
use sp1_stark::{
    baby_bear_poseidon2::BabyBearPoseidon2, Dom, ShardProof, StarkGenericConfig, StarkVerifyingKey,
};
use strum_macros::{EnumDiscriminants, EnumTryAs};

pub mod error;
mod verify;

/// The configuration for the core prover.
pub type CoreSC = BabyBearPoseidon2;

/// The configuration for the inner prover.
pub type InnerSC = BabyBearPoseidon2;

/// An intermediate proof which proves the execution.
#[derive(Clone, Serialize, Deserialize)]
#[serde(bound(serialize = "ShardProof<SC>: Serialize, Dom<SC>: Serialize"))]
#[serde(bound(
    deserialize = "ShardProof<SC>: serde::de::DeserializeOwned, Dom<SC>: serde::de::DeserializeOwned"
))]
pub struct SP1ReduceProof<SC: StarkGenericConfig> {
    /// The compress verifying key associated with the proof.
    pub vk: StarkVerifyingKey<SC>,
    /// The shard proof representing the compressed proof.
    pub proof: ShardProof<SC>,
}

impl<SC: StarkGenericConfig> core::fmt::Debug for SP1ReduceProof<SC> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("SP1ReduceProof")
            .field("vk", &"<StarkVerifyingKey>")
            .field("proof", &"<ShardProof>")
            .finish()
    }
}

/// A proof generated by the SP1 RISC-V zkVM.
/// Redefined due to SDK's non-no_std limitation, and is used only for deserialization.
#[derive(Debug, Clone, Serialize, Deserialize, EnumDiscriminants, EnumTryAs)]
#[strum_discriminants(derive(Default, Hash, PartialOrd, Ord))]
#[strum_discriminants(name(SP1ProofMode))]
pub enum SP1Proof {
    /// A proof generated by the core proof mode.
    ///
    /// The proof size scales linearly with the number of cycles.
    #[strum_discriminants(default)]
    Core(Vec<ShardProof<CoreSC>>),
    /// A proof generated by the compress proof mode.
    ///
    /// The proof size is constant, regardless of the number of cycles.
    Compressed(Box<SP1ReduceProof<InnerSC>>),
    /// A proof generated by the Plonk proof mode.
    Plonk(PlonkBn254Proof),
    /// A proof generated by the Groth16 proof mode.
    Groth16(Groth16Bn254Proof),
}

/// A zero-knowledge proof generated by the PLONK protocol with a Base64 encoded gnark PLONK proof.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PlonkBn254Proof {
    pub public_inputs: [String; 2],
    pub encoded_proof: String,
    pub raw_proof: String,
    pub plonk_vkey_hash: [u8; 32],
}

/// A zero-knowledge proof generated by the Groth16 protocol with a Base64 encoded gnark Groth16 proof.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Groth16Bn254Proof {
    pub public_inputs: [String; 2],
    pub encoded_proof: String,
    pub raw_proof: String,
    pub groth16_vkey_hash: [u8; 32],
}

/// The information necessary to verify a proof for a given RISC-V program.
#[derive(Clone, Serialize, Deserialize)]
pub struct SP1VerifyingKey {
    pub vk: StarkVerifyingKey<CoreSC>,
}

/// A STARK verifier for SP1 proofs.
pub struct StarkVerifier;

impl StarkVerifier {
    /// Verifies an SP1 compressed proof, as generated by the SP1 SDK.
    ///
    /// # Arguments
    ///
    /// * `proof` - The proof bytes.
    /// * `sp1_vk` - The SP1 verifying key bytes.
    ///
    /// # Returns
    ///
    /// A success [`Result`] if verification succeeds, or a [`StarkError`] if verification fails.
    pub fn verify(proof: &[u8], sp1_vk: &[u8]) -> Result<(), StarkError> {
        let proof: SP1Proof = bincode::deserialize(proof).expect("failed to deserialize the proof");
        let SP1Proof::Compressed(proof) = proof else { panic!("expected a compressed proof") };
        let vk: SP1VerifyingKey =
            bincode::deserialize(sp1_vk).expect("failed to deserialize the vk");

        verify::verify_compressed_algebraic(&proof, &vk)
    }
}
